name: Kotlin
main: xyz.gmitch215.kotlinmc.Spigot
version: ${project.ext.kotlin_version}
description: ${project.description}
api-version: 1.13
author: gmitch215
folia-supported: true
website: ${project.ext.url}
