name: Force Release
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  force-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Force Release
        run: bash scripts/release-version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}